---

- block:
    - name: "Create a snapshot of the factom_database volume"
      command: >
        gcloud compute disks snapshot
        {{ inventory_hostname }}-factom-database
        --snapshot-names {{ inventory_hostname }}-factom-database-{{ ansible_date_time.epoch }}
        --zone {{ zone }}
      delegate_to: localhost
  tags:
    - factomd_backup_database
