---

- block:
  - validate:
      schema:
        type: object
        additionalProperties:
          - command
        properties:
          project:
            type: string
          type:
            type: string
            enum:
              - image
              - snapshot
          zone:
            type: string
        required:
          - project
          - type
          - zone
      instance: "{{ factomd }}"
    register: factomd_validated

  - set_fact:
      factomd_v: "{{ factomd_validated.result }}"

  - import_role:
      name: bedrock.gcp
    vars:
      gcp:
        command: disk_image
        disk_name: "{{ inventory_hostname }}-factom-database"
        family: factom-database
        name: "{{ inventory_hostname }}-factom-database"
        project: "{{ factomd_v.project }}"
        zone: "{{ factomd_v.zone }}"
    when: factomd_v.type == 'image'

  - import_role:
      name: bedrock.gcp
    vars:
      gcp:
        command: disk_snapshot
        disk_name: "{{ inventory_hostname }}-factom-database"
        name: "{{ inventory_hostname }}-factom-database"
        project: "{{ factomd_v.project }}"
        zone: "{{ factomd_v.zone }}"
    when: factomd_v.type == 'snapshot'

  tags:
    - factomd_backup_database

