---

- block:
  - validate:
      schema:
        type: object
        additionalProperties:
          - command
        properties:
          project:
            type: string
          zone:
            type: string
        required:
          - zone
      instance: "{{ factomd }}"
    register: factomd_validated

  - set_fact:
      factomd_v: "{{ factomd_validated.result }}"

#  - import_role:
#      name: bedrock.gcp
#    vars:
#      gcp:
#        command: disk_image
#        disk_name: "{{ inventory_hostname }}-factom-database"
#        family: factom-database
#        name: "{{ inventory_hostname }}-factom-database"
#        project: "{{ factomd_v.project }}"
#        zone: "{{ factomd_v.zone }}"

  - import_role:
      name: bedrock.gcp
    vars:
      gcp:
        command: disk_snapshot
        disk_name: "{{ inventory_hostname }}-factom-database"
        name: "{{ inventory_hostname }}-factom-database"
        project: "{{ factomd_v.project }}"
        zone: "{{ factomd_v.zone }}"

  tags:
    - factomd_backup_database

