---

- block:
    - validate:
        schema:
          type: object
          properties:
            image:
              oneOf:
                - type: "null"
                - type: string
              default: null
            stackdriver_enable:
              type: boolean
              default: no
            state:
              type: string
              enum:
                - absent
                - present
                - started
                - stopped
          required:
            - stackdriver_enable
            - state
        instance: "{{ factomd }}"
      register: factomd_validated

    - set_fact:
        factomd_v: "{{ factomd_validated.result }}"

    - name: "Manage the factomd container: {{ factomd_v.state }}"
      docker_container:
        command: -startdelay=600 -faulttimeout=120 -config=/root/.factom/private/factomd.conf
        image: "{{ factomd_v.image }}"
        labels:
          name: factomd
        log_driver: "{{ stackdriver_enable | ternary('fluentd', None) }}"
        log_options:
          tag: factomd_docker
        name: factomd
        ports:
          - 8088:8088
          - 8090:8090
          - 8108:8108
        restart_policy: no
        volumes:
          - factom_database:/root/.factom/m2
          - factom_keys:/root/.factom/private
        state: "{{ factomd_v.state }}"
  tags:
    - factomd_container
