---

- name: "Delete all FastBoot files from the factom_database volume"
  file:
    name: "{{ item }}"
    state: absent
  with_fileglob:
    - "/mnt/docker_volumes/factom_database/FastBoot*"
  become: yes
