---

- name: "Delete all FastBoot files from the factom_database volume"
  shell: "rm /mnt/docker_volumes/factom_database/FastBoot*"
  args:
    warn: no
  register: factomd_rm_return
  changed_when:
    - factomd_rm_return is not failed
  failed_when:
    - factomd_rm_return is failed
    - "'No such file or directory' not in factomd_rm_return.stderr"
  become: yes
