---

- block:
    - validate:
        schema:
          type: object
          properties:
            external_network_interface:
              type: string
            network:
              type: string
              enum:
                - mainnet
                - testnet
            stackdriver_enabled:
              type: boolean
              default: no
            swarm_manager_host:
              type: string
              format: hostname
          required:
            - external_network_interface
            - network
            - stackdriver_enabled
            - swarm_manager_host
        instance: "{{ factomd }}"
      register: factomd_validated

    - set_fact:
        factomd_v: "{{ factomd_validated.result }}"

    - block:
        - name: "Allow swarm manager to access docker daemon"
          ufw:
            rule: allow
            from_ip: "{{ factomd_v.swarm_manager_host }}"
            proto: tcp
            to_port: 2376
          notify: os_ufw_rules_changed

        - name: "Restrict factomd console, api, and portainer ssh to swarm manager"
          iptables:
            action: insert
            chain: DOCKER-USER
            destination_port: "{{ item }}"
            in_interface: "{{ factomd_v.external_network_interface }}"
            jump: DROP
            match: tcp
            protocol: tcp
            source: "! {{ factomd_v.swarm_manager_host }}"
          notify: os_ufw_rules_changed
          loop:
            - 8088
            - 8090
            - 2222

        - name: "Install the factomd.conf template"
          template:
            dest: /mnt/docker_volumes/factom_keys/factomd.conf
            force: no
            src: factomd.conf.j2
      become: yes

    - block:
        - import_role:
            name: bedrock.stackdriver
          vars:
            stackdriver:
              command: configure_logging_agent
              config: |
                <source>
                  @type exec
                  <parse>
                    @type json
                  </parse>
                  tag factomd_heights
                  command curl -X POST --data-binary '{"jsonrpc": "2.0", "id": 0, "method": "heights"}' -H 'content-type:text/plain;' http://localhost:8088/v2
                  run_interval 1m
                </source>

                <filter factomd_heights>
                  @type record_transformer
                  enable_ruby
                  renew_record
                  <record>
                    hostname ${hostname}
                    directoryBlockHeight ${record["result"]["directoryblockheight"]}
                    entryBlockHeight ${record["result"]["entryblockheight"]}
                    entryHeight ${record["result"]["entryheight"]}
                    leaderHeight ${record["result"]["leaderheight"]}
                  </record>
                </filter>
              filename: factomd_heights

        - import_role:
            name: bedrock.stackdriver
          vars:
            stackdriver:
              command: configure_logging_agent
              config: |
                <filter factomd_docker>
                  @type record_transformer
                  enable_ruby
                  renew_record true
                  keep_keys container_name, source
                  <record>
                    hostname ${hostname}
                    message ${hostname + " " + record["log"]}
                  </record>
                </filter>
              filename: factomd_docker

        - import_role:
            name: bedrock.stackdriver
          vars:
            stackdriver:
              command: configure_monitoring_agent
              data_source_specification: record
              metric_descriptor_name: factomd/directory_block_height
              metric_type: GAUGE
              plugin_config: |
                LoadPlugin curl_json
                <Plugin curl_json>
                  <URL "http://localhost:8088/v2">
                    Header "content-type:text/plain;"
                    Instance "factomd_directory_block_height"
                    Interval 60
                    Post "{\"jsonrpc\": \"2.0\", \"id\": 0, \"method\": \"heights\"}"

                    <Key "result/directoryblockheight">
                      Type "gauge"
                    </Key>
                  </URL>
                </Plugin>
              plugin_instance: factomd_directory_block_height

        - import_role:
            name: bedrock.stackdriver
          vars:
            stackdriver:
              command: configure_monitoring_agent
              data_source_specification: record
              metric_descriptor_name: factomd/entry_block_height
              metric_type: GAUGE
              plugin_config: |
                LoadPlugin curl_json
                <Plugin curl_json>
                  <URL "http://localhost:8088/v2">
                    Header "content-type:text/plain;"
                    Instance "factomd_entry_block_height"
                    Interval 60
                    Post "{\"jsonrpc\": \"2.0\", \"id\": 0, \"method\": \"heights\"}"

                    <Key "result/entryblockheight">
                      Type "gauge"
                    </Key>
                  </URL>
                </Plugin>
              plugin_instance: factomd_entry_block_height

        - import_role:
            name: bedrock.stackdriver
          vars:
            stackdriver:
              command: configure_monitoring_agent
              data_source_specification: record
              metric_descriptor_name: factomd/entry_height
              metric_type: GAUGE
              plugin_config: |
                LoadPlugin curl_json
                <Plugin curl_json>
                  <URL "http://localhost:8088/v2">
                    Header "content-type:text/plain;"
                    Instance "factomd_entry_height"
                    Interval 60
                    Post "{\"jsonrpc\": \"2.0\", \"id\": 0, \"method\": \"heights\"}"

                    <Key "result/entryheight">
                      Type "gauge"
                    </Key>
                  </URL>
                </Plugin>
              plugin_instance: factomd_entry_height

        - import_role:
            name: bedrock.stackdriver
          vars:
            stackdriver:
              command: configure_monitoring_agent
              data_source_specification: record
              metric_descriptor_name: factomd/leader_height
              metric_type: GAUGE
              plugin_config: |
                LoadPlugin curl_json
                <Plugin curl_json>
                  <URL "http://localhost:8088/v2">
                    Header "content-type:text/plain;"
                    Instance "factomd_leader_height"
                    Interval 60
                    Post "{\"jsonrpc\": \"2.0\", \"id\": 0, \"method\": \"heights\"}"

                    <Key "result/leaderheight">
                      Type "gauge"
                    </Key>
                  </URL>
                </Plugin>
              plugin_instance: factomd_leader_height
      when: factomd_v.stackdriver_enabled
  tags:
    - factomd_install
