---

- validate:
    schema:
      type: object
      properties:
        build:
          type: string
          enum:
            - stable
            - edge
          default: stable
        database_volume_device:
          type: string
        keys_volume_device:
          type: string
        swarm_manager_host:
          type: string
          format: hostname
        swarm_token:
          type: string
        tls_cert_url:
          type: string
          format: uri
          default: https://raw.githubusercontent.com/FactomProject/factomd-authority-toolkit/master/tls/cert.pem
        tls_key_url:
          type: string
          format: uri
          default: https://raw.githubusercontent.com/FactomProject/factomd-authority-toolkit/master/tls/key.pem
        user:
          type: string
          default: ubuntu
      required:
        - build
        - database_volume_device
        - keys_volume_device
        - swarm_manager_host
        - swarm_token
        - tls_cert_url
        - tls_key_url
    instance: "{{ factomd }}"
  register: factomd_validated

- set_fact:
    factomd_v: "{{ factomd_validated.result }}"

- import_role:
    name: jcheroske.docker
  vars:
    docker:
      command: download_tls_cert_and_key
      cert_url: "{{ factomd_v.tls_cert_url }}"
      key_url: "{{ factomd_v.tls_key_url }}"

- import_role:
    name: jcheroske.docker
  vars:
    docker:
      command: install
      build: "{{ factomd_v.build }}"
      user: "{{ factomd_v.user }}"

- import_role:
    name: jcheroske.docker
  vars:
    docker:
      command: local_volume_from_device
      device: "{{ factomd_v.database_volume_device }}"
      name: factom_database

- import_role:
    name: jcheroske.docker
  vars:
    docker:
      command: local_volume_from_device
      device: "{{ factomd_v.keys_volume_device }}"
      name: factom_keys

- import_role:
    name: jcheroske.docker
  vars:
    docker:
      command: swarm_node
      manager_host: "{{ factomd_v.swarm_manager_host }}"
      token: "{{ factomd_v.swarm_token }}"

- block:
    - name: "Allow swarm manager to access docker daemon"
      ufw:
        rule: allow
        from_ip: "{{ factomd_v.swarm_manager_host }}"
        proto: tcp
        to_port: 2376

    - name: "Restrict container ports to swarm manager"
      iptables:
        chain: DOCKER_USER
        destination_port: "{{ item }}"
        in_interface: ! docker0
        jump: DROP
        match: tcp
        out_interface: docker0
        protocol: tcp
        source: "! {{ factomd_v.swarm_manager_host }}"
      loop:
        - 2222
        - 8088
        - 8090
  become: yes