---

- validate:
    schema:
      type: object
      properties:
        command:
          type: string
          enum:
            - change_acks_height
            - container
            - dependency
            - identity
            - install
      required:
        - command
    instance: "{{ factomd }}"

- include_tasks: '{{ factomd.command }}.yml'
  when: factomd.command != 'dependency'
